valetbike/config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get '/bikes', to: 'bikes#index'
  get '/stations', to: 'stations#index'
  get '/stations/:id', to: 'stations#show', as: 'station'
  get '/return', to: 'bikes#index'
  get '/users', to: 'users#index'
  resources :rentals
  resources :users do
    get 'history', on: :member
  end
  get '/about', to: 'about#index'
  get '/signup', to: 'users#new', as: 'signup'
  resources :users, only: [:create, :update, :edit, :show, :destroy]
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :bikes do
    member do
      patch 'return'  # PATCH request to handle the return action for a specific bike
    end
  end
  post 'create-checkout-session', to: 'stripe#create_checkout_session'
  get '/stripe/success', to: 'stripe#success', as: 'stripe_success'
end

valetbike/app/views/layouts/_footer.html.erb
<footer>
    <p>
        <a href="https://maps.app.goo.gl/B4EbLtQsMQ9Fzfwu7">1 Chapin Way Northampton, MA 01063 | </a>
        1-800-BICYCLE |
        <a href="mailto:help@vectorbike.com">help@vectorbike.com</a>
    </p>
</footer>

valetbike/app/views/layouts/_header.html.erb
<ul>
    <li><%= link_to(image_tag('viktor_snail.png', alt: 'Viktor icon'), root_path) %></li>
    <% if user_signed_in? %>
    <li><%= button_to 'Log Out', logout_path, method: :delete, class: "header" %></li>
    <%= link_to user_path(current_user), class: "header" do %>
    Profile
    <% end %>
    <% else %>
    <%= link_to signup_path, class: "header" do %>
    Sign Up
    <% end %>
    <%= link_to login_path, class: "header" do %>
    Sign In
    <% end %>
    <% end %>
    <% if active_rental? %>
    <%# if there is an active rental, link to rental list page %>
    <%= link_to rentals_path, class: "header" do %>
    Rent
    <% end %>
    <% else %>
    <%= link_to stations_path, class: "header" do %>
    Rent
    <% end %>
    <% end %>
    <%= link_to about_path, class: "header" do %>
    About
    <% end %>
    <%= link_to root_path, class: "header" do %>
    Home
    <% end %>
</ul>

valetbike/app/views/layouts/_map.html.erb
<div style="aspect-ratio: 1; width: 100%; overflow: hidden; border-radius:5px;">
    <iframe src="https://www.google.com/maps/d/u/0/embed?mid=1OkN_Nbs463ViM0_sYR07xKnuvRJ7uXA&ehbc=2E312F&noprof=1" style="width: 100%; height: 100%;"></iframe>
</div>

valetbike/app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css?family=Rubik:400,500,700" rel="stylesheet" type="text/css">
    <link href="/favicon.ico" rel="icon" type="image/x-icon">
    <title>VectorBike</title>
</head>

<body>
    <div id="site-container" class="flexbox vertical stretch flex-1">
        <div class="flexbox vertical center">
            <%= yield %>
        </div>
    </div>
    <%= render "layouts/footer" %>
</body>

</html>