valetbike/config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get '/bikes', to: 'bikes#index'
  get '/stations', to: 'stations#index'
  get '/stations/:id', to: 'stations#show', as: 'station'
  get '/return', to: 'bikes#index'
  get '/users', to: 'users#index'
  resources :rentals
  resources :users do
    get 'history', on: :member
  end
  get '/about', to: 'about#index'
  get '/signup', to: 'users#new', as: 'signup'
  resources :users, only: [:create, :update, :edit, :show, :destroy]
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :bikes do
    member do
      patch 'return'  # PATCH request to handle the return action for a specific bike
    end
  end
  post 'create-checkout-session', to: 'stripe#create_checkout_session'
  get '/stripe/success', to: 'stripe#success', as: 'stripe_success'
end

valetbike/app/models/station.rb
class Station < ApplicationRecord
  validates_presence_of    :identifier,
                           :name,
                           :address
  validates_uniqueness_of  :identifier
  attribute :capacity, :integer
  attribute :lat, :float
  attribute :long, :float

  has_many :docked_bikes, class_name: :Bike, foreign_key: :current_station_id

end

valetbike/app/controllers/stations_controller.rb
class StationsController < ApplicationController
  include StationsHelper
  def index
    if params[:sort] == "available_bikes"
      @stations = Station.all.sort_by { |station| count_available_bikes(station) }.reverse
    else
      @stations = Station.all.order(params[:sort])
    end
    @view = params[:view] || 'map'
  end

  def show
    @station = Station.find(params[:id])
  end

end

valetbike/app/helpers/stations_helper.rb
module StationsHelper
  def count_available_bikes(station)
    return station.docked_bikes.select{ |bike| bike[:status] == "available" }.count
  end

  def bikes_available_sorted(station)
    return station.docked_bikes.select{ |bike| bike[:status] == "available"}.sort_by{|bike| -bike.charge}
  end
end

valetbike/app/views/stations/_dropdown.html.erb
<div>
    <div id="stationDropdown" class="dropdown-content">
        <input type="text" placeholder="Search..." id="input" onkeyup="filterFunction()">
        <% stations.sort_by{|station| station.name}.each do |station| %>
        <% if count_available_bikes(station) !=0 %>
        <%= link_to station.name, station_path(station.id) %>
        <% end %>
        <% end %>
    </div>
</div>

<script>
    function filterFunction() {
        var input, filter, ul, li, a, i;
        input = document.getElementById("input");
        filter = input.value.toUpperCase();
        div = document.getElementById("stationDropdown");
        a = div.getElementsByTagName("a");
        for (i = 0; i < a.length; i++) {
            txtValue = a[i].textContent || a[i].innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                a[i].style.display = "";
            } else {
                a[i].style.display = "none";
            }
        }
    }
</script>

valetbike/app/views/stations/_form.html.erb
<%= javascript_include_tag "pop_up", "data-turbolinks-track" => true  %>
<%# displays flash alert if there is one %>
<% if flash[:alert] %>
<div id="flash" onclick="close_flash()">
    <%= flash[:alert] %>
</div>
<% end %>
<h1><strong>Available Bikes:</strong></h1>
<%# did not use model: @rental because arguments were not being wrapped in rental key, using name: rental[attribute] syntax instead %>
<div class="bike-form">
    <%= form_with(url: rentals_path, local: true) do |form| %>
    <%# if there are bikes at the station, display and allow user to select one%>
    <% if count_available_bikes(@station).present? %>
    <% bikes_available_sorted(@station).each do |bike|%>
    <label class="radio-button-container">
        <%= form.radio_button :bike_id, bike.id, name: "rental[bike_id]", class: "custom-radio" %>
        <%= form.label :bike_id, "Bike ##{bike.id}, #{bike.charge}% Charged", value: bike.id %>
        <span class="radio"></span>
    </label>
    <% end %>
    <div class="form-container">
        <%# allow user to select duration of ride %>
        <h1><strong>Select Ride Duration:</strong></h1>
        <%= form.select :duration, [
                ["15 minutes", 15],
                ["30 minutes", 30],
                ["45 minutes", 45],
                ["1 Hour", 60],
                ["1 Hour 15 Minutes", 75],
                ["1 Hour 30 Minutes", 90],
                ["1 Hour 45 Minutes", 105],
                ["2 Hours", 120]], {}, name: "rental[duration]",
                id: "dropdown"
            %>
        <%# hidden fields %>
        <%# placeholder, we will generate identifiers later %>
        <%= form.hidden_field :identifier, value: generate_rental_id(), name: "rental[identifier]"%>
        <%# init overtime to false %>
        <%= form.hidden_field :over_time, value: false, name: "rental[over_time]" %>
        <%# hardcode user id %>
        <%# hardcode user id %>

        <% if current_user.nil? %>
        <%= form.hidden_field :user_id, value: 0, name: "rental[user_id]" %>
        <% else %>
        <%= form.hidden_field :user_id, value: current_user.id, name: "rental[user_id]" %>
        <% end %>

        <%# submit form %>
        <div class="button-container">
            <%= form.submit "Rent Now!", class: "submit button" %>
            <%= link_to stations_path(), class: "return button" do %>
            Return to Stations
            <% end %>
        </div>
        <% else %>
        <%# if there are no bikes available, display the message %>
        <div class="empty">No bikes currently available at this station.</div>
        <div class="button-container" style="display: flex; justify-content: center; align-items: center;">
            <%= link_to stations_path(), class: "return button" do %>
            Return to Stations
            <% end %>
        </div>
        <% end %>
        <% end %>
    </div>

valetbike/app/views/stations/_row.html.erb
<div class="record-row <%= cycle "odd", "even", name: "row-cycler" %> flexbox vertical stretch">
    <div class="flexbox">
        <%= link_to station_path(station.id) do %>
        <%= station.identifier %>: <%= station.name %> (<%= station.address %>)
        <% end %>
    </div>
</div>

valetbike/app/views/stations/_stations.html.erb
<table class="styled-table" width=85%>
    <thead>
        <tr>
            <th id="station-name">
                <span><%= link_to "Station Name", :sort => "name", view: @view%> </span>
            </th>
            <th id="address">
                <span><%= link_to "Address", :sort => "address", view: @view%> </span>
            </th>
            <th id="available-bikes">
                <span><%= link_to "Available Bikes", :sort => "available_bikes", view: @view%> </span>
            </th>
        </tr>
    </thead>

    <tbody class="active-row">
        <% stations.each do |station| %>
        <tr class="link">
            <%= link_to station_path(station.id) do %>
            <td><%= link_to station.name, station_path(station.id) %></td>
            <td><%= link_to station.address, station_path(station.id) %></td>
            <td><%= link_to count_available_bikes(station), station_path(station.id) %></td>
            <% end %>
        </tr>
        <% end %>
    </tbody>
</table>

valetbike/app/views/stations/_toggle.html.erb
<div class="button_container">
    <div class="toggle_button">
        <%= link_to "Map View", stations_path(view: "map"), class: "toggle_button #{'active' if @view == 'map'}" %>
    </div>
    <div class="toggle_button">
        <%= link_to "List View", stations_path(view: "list"), class: "toggle_button #{'active' if @view == 'list'}" %>
    </div>
</div>

valetbike/app/views/stations/index.html.erb
<%= render(partial: 'layouts/header') %>
<div class="page-section flexbox vertical stretch">
    <div class="section-title-centered">
        Rent a Bike!
    </div>
    <%= render(partial: 'stations/toggle') %>
    <center>
        <br>
        <p>To rent a bike, select the station you would like to rent from. This will bring you to a bike rental form. You'll be able to return your bike to any station at the end of your ride.</p>
    </center>
    <div>
        <% if @view == 'map' %>
        <br>
        <div>
            <div class="map-container">
                <div style="width:70%;">
                    <%= render(partial: 'layouts/map') %>
                </div>
                <div style="width:20%;">
                    <%= render "dropdown", stations: @stations %>
                </div>
            </div>
        </div>
        <% else %>
        <% if @stations.present? %>
        <div class="max-w-7xl mx-auto mt-12">
            <center>
                <%= render "stations", stations: @stations %>
            </center>
        </div>
        <% else %>
        <div class="empty">
            No stations found.
        </div>
        <% end %>
        <% end %>
    </div>
</div>
</div>

valetbike/app/views/stations/show.html.erb
<style>
    footer {
        /* positions footer at bottom of page when page content does not fill view*/
        position: absolute;
        bottom: 0;
        width: 100%;
    }
</style>
<%= render(partial: 'layouts/header') %>
<div class="page-section flexbox vertical stretch">
    <div class="section-inner flexbox vertical stretch">
        <div class="section-title">
            <%= @station.name %> (<%= @station.address %>)
        </div>
    </div>
</div>
<%= render(partial: "form") %>