valetbike/config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get '/bikes', to: 'bikes#index'
  get '/stations', to: 'stations#index'
  get '/stations/:id', to: 'stations#show', as: 'station'
  get '/return', to: 'bikes#index'
  get '/users', to: 'users#index'
  resources :rentals
  resources :users do
    get 'history', on: :member
  end
  get '/about', to: 'about#index'
  get '/signup', to: 'users#new', as: 'signup'
  resources :users, only: [:create, :update, :edit, :show, :destroy]
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :bikes do
    member do
      patch 'return'  # PATCH request to handle the return action for a specific bike
    end
  end
  post 'create-checkout-session', to: 'stripe#create_checkout_session'
  get '/stripe/success', to: 'stripe#success', as: 'stripe_success'
end

valetbike/app/models/rental.rb
class Rental < ApplicationRecord
  validates_presence_of    :identifier
  validates_uniqueness_of  :identifier
  validates_presence_of :bike_id
  attribute :start_time, :datetime
  attribute :end_time, :datetime
  attribute :over_time, :boolean
  attribute :duration, :integer
  attribute :active, :boolean

  belongs_to :user, optional: true
  belongs_to :bike
end

valetbike/app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: %i[ show edit update destroy ]
  before_action :authenticate_user

  # GET /rentals or /rentals.json
  def index
    @rentals = Rental.all
    @user = User.find(session[:user_id])
  end

  # GET /rentals/1 or /rentals/1.json
  def show
    @rental = Rental.find(params[:id])
    @bike = Bike.find(@rental.id)
    @stations = Station.all
  end

  # GET /rentals/new
  def new
    @rental = Rental.new
  end

  # GET /rentals/1/edit
  def edit
  end

  # returns if the user has five rentals, false if less than, true if five
  def five_rentals?
    return (Rental.where(user_id: session[:user_id], active: true).count == 5)
  end

  # POST /rentals or /rentals.json
  def create
    @rental = Rental.new(rental_params)
    amount = rental_cost(@rental.duration)
    respond_to do |format|
    # check if user already has five active rentals, then display flash message and do not save rental
    if five_rentals?
      format.html do
        flash.alert = "You can only rent five bikes at once."
        redirect_to rentals_path, status: :unprocessable_entity
      end
      format.json { render json: @rental.errors, status: :unprocessable_entity }
    elsif (current_user.balance || 0) < amount
      format.html do
        flash.alert = "You do not have sufficient funds to rent this bike."
        redirect_to rentals_path, status: :unprocessable_entity
      end
      format.json { render json: @rental.errors, status: :unprocessable_entity }
    elsif @rental.save
      # if the rental is valid...
      # update user's balance to reflect purchase
      current_user.update_attribute(:balance, current_user.balance - amount)
      # update start and end time of rental
      @rental.update(start_time: @rental.created_at, end_time: @rental.created_at + @rental.duration.minutes, active: true)
      # find bike associated with rental, and update it so it is not at a station and is rented
      bike = Bike.find_by(id: @rental.bike_id)
      bike.update(status: "rented", current_station_id: nil)
      # redirct user to the page for their rental
      format.html { redirect_to rental_path(@rental), notice: "Rental was successfully created."}
    else
       # else, display flash alert and refresh the page for the current station
      format.html do
        flash.alert = "Please select a bike."
        redirect_to stations_path(@station), status: :unprocessable_entity
      end
      format.json { render json: @rental.errors, status: :unprocessable_entity }
    end
    end
  end

  # PATCH/PUT /rentals/1 or /rentals/1.json
  def update
    respond_to do |format|
      if @rental.update(rental_params)
        format.html { redirect_to rental_url(@rental), notice: "Rental was successfully updated." }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentals/1 or /rentals/1.json
  def destroy
    @rental.destroy

    respond_to do |format|
      format.html { redirect_to rentals_url, notice: "Rental was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # cost of each rental duration
  def rental_cost(duration)
    case duration
      when 15
        return 2.0
      when 30
        return 3.0
      when 45
        return 4.0
      when 60
        return 5.0
      when 75
        return 6.0
      when 90
        return 7.0
      when 105
        return 8.0
      when 120
        return 9.0
      else
        return 0.0
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental
      @rental = Rental.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rental_params
      params.require(:rental).permit(:bike_id, :end_time, :identifier, :start_time, :over_time, :user_id, :duration)
    end
end

valetbike/app/helpers/rentals_helper.rb
module RentalsHelper
  RENTAL_NUMBER_RANGE = (10_000..99_999)

  def generate_rental_id()
    rental_id = loop do
      number = rand(RENTAL_NUMBER_RANGE)
      break number unless Rental.exists?(identifier: number)
    end
    return rental_id
  end
end

valetbike/app/views/rentals/_rentals.html.erb
<table class="styled-table" width=85%>
    <thead>
        <tr>
            <th class="no-link" id="rental-number">
                <span><%="Rental Number"%> </span>
            </th>
            <th class="no-link" id="start_time">
                <span><%="Start Time"%> </span>
            </th>
            <th class="no-link" id="end_time">
                <span><%="End Time"%></span>
            </th>
            <th class="no-link" id="bike_id">
                <span><%="Bike ID"%></span>
            </th>
        </tr>
    </thead>

    <tbody class="active-row">
        <% rentals.each_with_index do |rental, i| %>
        <tr class="link">
            <%= link_to rental_path(rental.id) do %>
            <td><%= link_to i + 1, rental_path(rental.id) %></td>
            <td><%= link_to rental.start_time.strftime("%H:%M") , rental_path(rental.id) %></td>
            <td><%= link_to rental.end_time.strftime("%H:%M") , rental_path(rental.id) %></td>
            <td><%= link_to rental.bike_id, rental_path(rental.id) %></td>
            <% end %>
        </tr>
        <% end %>
    </tbody>
</table>

valetbike/app/views/rentals/error.html.erb
<div class="error">
    <h1>There was an error creating the rental.</h1>
    <p><%= notice %></p>
</div>

valetbike/app/views/rentals/index.html.erb
<%= render(partial: 'layouts/header') %>
<div class="page-section flexbox vertical stretch">
    <div class="section-title-centered">
        Active Rentals
    </div>
    <center>
        <div style="font-size: 18px;">
            <p>Click on a rental to view your rental countdown or return your bike.</p>
        </div>
    </center>
    <div>
        <% @rentals = Rental.where(user_id: @user.id, active: true) %>
        <div class="max-w-7xl mx-auto mt-12">
            <center>
                <%= render "rentals", rentals: @rentals %>
                <% if Rental.where(user_id: session[:user_id], active: true).count < 5 %>
                <%# button %>
                <%= link_to stations_path, class: "button" do %>
                Rent Another Bike
                <% end %>
                <% else %>
                <p>You have reached the maximum number of current bike rentals.</p>
                <% end %>
            </center>
        </div>
    </div>
</div>

valetbike/app/views/rentals/show.html.erb
<%# imports pop up js file %>
<%= javascript_include_tag "pop_up", "data-turbolinks-track" => true  %>
<style>
    footer {
        /* positions footer at bottom of page when page content does not fill view*/
        position: absolute;
        bottom: 0;
        width: 100%;
    }
</style>
<%= render(partial: 'layouts/header') %>
<div class="page-section flexbox vertical stretch">
    <div class="section-inner flexbox vertical stretch">
        <br><br>
        <div style="text-align: center; font-size: 60px;" class="section-title">
            Success!
        </div>
        <div style="text-align: center;" class="section-title">
            Enjoy your ride!
        </div>
        <h1 style="text-align: center;">Your ride ends in...</h1>
        <div style="font-size: 2rem; font-weight: bold; color: #1F487E; text-align: center;" id="countdown">
            &nbsp;
        </div>
        <br><br>
        <div style="align-self: center; text-align: center;"><%= image_tag('viktor_snail.png', alt: 'Bike icon', style: 'width: 100px;') %></div>
        <br><br>
        <% if flash[:alert] %>
        <div id="flash" onclick="close_flash()">
            <%= flash[:alert] %>
        </div>
        <% end %>
        <%= link_to rentals_path, class: "button" do %>
        View Active Rentals
        <% end %>
        <div class="button" onclick="popup()">
            Return Your Bike
        </div>
        <br><br>
        <div id="popup" style="display: none; position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); background: white; padding: 20px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); text-align: right">
            <div style="text-align: left;">
                <h1>Would you like to return your bike?</h1>
                <p>We hoped you enjoyed your ride.</p>
                <%# form to return the bike to a specific station %>
                <%# @rental.bike_id ensures that the bike_id is being passed as id, not the rental id %>
                <%= form_with url: return_bike_path(@rental.bike_id), method: :patch, local: true do |form| %>
                <%= form.hidden_field :current_bike_id, value: @rental.bike_id %>
                <%= form.hidden_field :current_rental_id, value: @rental.id %>
                <div>
                    <%# text field for the user to enter return station id %>
                    <%= form.select :station_id, @stations.map {|station| [station.name, station.id]}.sort, { prompt: "Select a Station" }, id: "dropdown" %>
                </div>
                <div style="display: flex; justify-content: space-around; margin: 0% 30%">
                    <%# button to close popup (not return the bike) %>
                    <div class="button return" onclick="close_popup()">
                        Close
                    </div>
                    <%# button to submit the bike return %>
                    <%= form.submit 'Return', class: "button submit" %>
                </div>
                <% end %>
            </div>
        </div>
        <script>
            // set the time we are counting down to
            var countdown_time = new Date("<%= @rental.end_time %>").getTime();

            // update count every second
            var x = setInterval(function() {

                // get current date/time
                var current_time = new Date().getTime();

                // find time left between now and count down time
                var time_left = countdown_time - current_time;

                // find hours, minutes and seconds left
                var hours = Math.floor((time_left % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                var minutes = Math.floor((time_left % (1000 * 60 * 60)) / (1000 * 60));
                var seconds = Math.floor((time_left % (1000 * 60)) / 1000);

                // convert 1 digit to 00 format strings
                if (hours < 10) {
                    hours = "0" + hours.toString()
                } else {
                    hours = hours.toString()
                }
                if (minutes < 10) {
                    minutes = "0" + minutes.toString()
                } else {
                    minutes = minutes.toString()
                }
                if (seconds < 10) {
                    seconds = "0" + seconds.toString()
                } else {
                    seconds = seconds.toString()
                }

                if (document.getElementById("countdown") != null) {
                    // show result in countdown div, formatted correctly
                    document.getElementById("countdown").innerHTML = hours + ":" +
                        minutes + ":" + seconds;

                    // if the ride is over, say it is over
                    if (time_left < 0) {
                        clearInterval(x);
                        document.getElementById("countdown").innerHTML = "Your rental is over time.";
                    }
                }
            }, 1000);
        </script>