valetbike/config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get '/bikes', to: 'bikes#index'
  get '/stations', to: 'stations#index'
  get '/stations/:id', to: 'stations#show', as: 'station'
  get '/return', to: 'bikes#index'
  get '/users', to: 'users#index'
  resources :rentals
  resources :users do
    get 'history', on: :member
  end
  get '/about', to: 'about#index'
  get '/signup', to: 'users#new', as: 'signup'
  resources :users, only: [:create, :update, :edit, :show, :destroy]
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :bikes do
    member do
      patch 'return'  # PATCH request to handle the return action for a specific bike
    end
  end
  post 'create-checkout-session', to: 'stripe#create_checkout_session'
  get '/stripe/success', to: 'stripe#success', as: 'stripe_success'
end

valetbike/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :identifier, presence: true, numericality: true, uniqueness: true
  validates :username, presence: true, uniqueness: true, length: { maximum: 20, too_long: "%{count} characters is the maximum allowed" }
  validates :first, presence: { message: "name can't be blank" }
  validates :last, presence: { message: "name can't be blank" }
  validates :email, presence: true, uniqueness: true, format: { with: /\A(.+)@(.+)\z/, message: "invalid"  }
  validates :password, length: { minimum: 8 }
  attribute :hours, :float
  attribute :balance, :float

  has_many :rentals
end

# do we actually validate length of password?

valetbike/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update ]
  before_action :validate_user_profile_page, only: [:show]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: 'User was successfully created.'
    else
      flash.now[:alert] = @user.errors.full_messages.join(", ")
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Profile updated successfully.'
    else
      flash.now[:alert] = @user.errors.full_messages.join(", ")
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    session[:user_id] = nil
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_path, flash: { success: 'Deleted Profile Successfully' } }
    end
  end

  def validate_user_profile_page
    @user = User.find(params[:id])

    if current_user != @user
      redirect_to root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:identifier, :username, :first, :last, :email, :password, :balance)
    end
end

valetbike/app/helpers/users_helper.rb
module UsersHelper
  USER_NUMBER_RANGE=(1_000..9_999)
  def generate_user_id()
    user_id = loop do
      number = rand(USER_NUMBER_RANGE)
      break number unless User.exists?(identifier: number)
    end
    return user_id
  end
end

valetbike/app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |form| %>
<div class="form-container">
    <%# <%= @user.errors.full_messages.inspect %>
    <div>
        <%# <%= form.label :identifier %>
        <%= form.hidden_field :identifier, value: generate_user_id() , class:"field" %>
    </div>
    <div>
        <%# <%= form.label :email %>
        <%= form.email_field :email, placeholder:"Enter Email", class:"field" %>
    </div>
    <div>
        <%# <%= form.label :first %>
        <%= form.text_field :first,  placeholder:"First Name" , class:"field" %>
    </div>
    <div>
        <%# <%= form.label :last %>
        <%= form.text_field :last , placeholder:"Last Name" , class:"field"%>
    </div>
    <div>
        <%# <%= form.label :username %>
        <%= form.text_field :username , placeholder:"Create a Username" , class:"field"%>
    </div>
    <div>
        <%# <%= form.label :password %>
        <%= form.password_field :password , placeholder:"Create a Password" , class:"field"%>
        <p class="subscript">Minimum of 8 characters</p>
    </div>
    <%= form.submit "Start Riding!", class:"submit button" %>
    <% end %>
</div>

valetbike/app/views/users/_history.html.erb
<table class="styled-table" id="history-table" width=85%>
    <thead>
        <tr>
            <th class="no-link" id="rental-number">
                <span><%="Rental Number"%> </span>
            </th>
            <th class="no-link" id="start_time">
                <span><%="Start Time"%> </span>
            </th>
            <th class="no-link" id="end_time">
                <span><%="End Time"%></span>
            </th>
            <th class="no-link" id="duration">
                <span><%="Duration"%></span>
            </th>
            <th class="no-link" id="bike_id">
                <span><%="Bike ID"%></span>
            </th>
            <th class="no-link" id="over_time">
                <span><%="Overtime"%></span>
            </th>
        </tr>
    </thead>

    <tbody class="active-row">
        <% rentals.each_with_index do |rental, i| %>
        <tr class="no-link">
            <td class="no-link"><%= i + 1 %></td>
            <td class="no-link"><%= rental.start_time.strftime("%H:%M") %></td>
            <td class="no-link"><%= rental.end_time.strftime("%H:%M") %></td>
            <td class="no-link"><%= rental.duration %> minutes</td>
            <td class="no-link"><%= rental.bike_id %></td>
            <td class="no-link"><% if rental.over_time == true %>
                <span style="color: red; font-weight: bold;">Yes</span>
                <% else %>
                No
                <% end %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

valetbike/app/views/users/edit.html.erb
<%= render(partial: 'layouts/header') %>
<div class="page-section flexbox vertical stretch">
    <div class="section-inner flexbox vertical stretch">
        <div class="section-title-centered" style="margin: 2rem 0px .5rem 0px">
            Edit Profile!
        </div>
    </div>
</div>
<% if flash[:alert] %>
<div class="alert alert-danger">
    <%= flash[:alert] %>
</div>
<% end %>
<%= form_with(model: @user, local: true) do |form| %>
<div>
    <%= form.text_field :first , placeholder:"Update First Name" , class:"field"%>
</div>
<div>
    <%= form.text_field :last , placeholder:"Update Last Name" , class:"field"%>
</div>
<div>
    <%= form.email_field :email, placeholder:"Update Email", class:"field" %>
</div>
<div>
    <%= form.text_field :username, placeholder:"Update Username", class:"field" %>
</div>
<div>
    <%= form.password_field :password , placeholder:"Update Password" , class:"field"%>
    <p class="subscript">Minimum of 8 characters</p>
</div>
<div class="actions">
    <%= form.submit 'Update Profile', class:"submit button" %>
</div>
<% end %>

valetbike/app/views/users/index.html.erb
<%= render(partial: 'layouts/header') %>
<h1>User profile</h1>

valetbike/app/views/users/new.html.erb
<%= javascript_include_tag "pop_up", "data-turbolinks-track" => true  %>
<%= render(partial: 'layouts/header') %>
<div class="page-section flexbox vertical stretch">
    <div class="section-inner flexbox vertical stretch">
        <div class="section-title-centered" style="margin: 2rem 0px .5rem 0px">
            Sign Up!
        </div>
    </div>
</div>
<% if flash[:alert] %>
<div id="flash" onclick="close_flash()">
    <%= flash[:alert] %>
</div>
<% end %>
<%= render(partial: "form") %>

valetbike/app/views/users/show.html.erb
<%# imports pop up js file %>
<%= javascript_include_tag "pop_up", "data-turbolinks-track" => true  %>
<%= render(partial: 'layouts/header') %>
<div class="page-section flexbox vertical stretch">
    <div class="section-inner flexbox vertical stretch">
        <% if flash[:notice] %>
        <div id="flash" onclick="close_flash()" style="background-color:green;">
            <%= flash[:notice] %>
        </div>
        <% end %>
        <br>
        <br>
        <div="container">
            <div class="row">
                <div class="column">
                    <div class="box1">
                        <div class="container">
                            <div class="section-title-centered">
                                Hello, <%= @user.first %>!
                                <% top_users = User.order(hours: :desc).limit(10) %>
                                <% if top_users.include?(@user) %>
                                <div class="tooltip">
                                    <span style="display: inline-block; vertical-align: top; margin-left: 10px;">
                                        <%= image_tag('top_ten_badge.png', alt: 'Top Ten Badge', style: 'width: 60px;') %>
                                        <span class="tooltiptext">You are in our top ten riders!</span>
                                    </span>
                                </div>
                                <% end %>
                            </div>
                        </div>
                        <%= link_to edit_user_path(current_user), class: "profile_button" do %>
                        Edit Profile
                        <% end %>
                        <div class="profile_button" onclick="popup()">
                            Delete Profile
                        </div>
                        <br>
                        <br>
                        <h1>Account Information</h1>
                        <div style="font-size: 18px;">
                        <br>
                        <div class="flexbox">
                            First Name: <%= @user.first %>
                        </div>
                        <br>
                        <div class="flexbox">
                            Last Name: <%= @user.last %>
                        </div>
                        <br>
                        <div class="flexbox">
                            Userame: <%= @user.username %>
                        </div>
                        <br>
                        <div class="flexbox">
                            Email: <%= @user.email %>
                        </div>
                        <br>
                        <div class="flexbox">
                            Balance: $<%= sprintf("%.2f", @user.balance || 0.0) %>
                        </div>
                        <br>
                        </div>
                        <script src="https://js.stripe.com/v3/"></script>
                        <button class="profile_button" id="checkout-button">Add Funds</button>
                    </div>
                </div>
                <div class="column">
                    <div class="speech-box">
                        <%# display number of hours a user has biked in whole hours %>
                        Congrats, you have biked <%= (@user.hours || 0).truncate() %> hours on <%= Rental.where(user_id: @user.id).count %> rides!
                    </div>
                    <div="container">
                        <div style="align-self: center; text-align: center;"><%= image_tag('flipped_viktor.png', alt: 'Flipped_Snail', style: 'width: 100px;') %></div>
                    <div class="box" id="table_box">
                        <h1 style="position: sticky; top: 0; background-color:var(--polynesian-blue-color); margin-left: 10px; padding-top: 10px; padding-bottom: 10px;">Your Rental History</h1>
                        <% @rentals = Rental.where(user_id: current_user.id, active: false) %>
                        <div class="max-w-7xl mx-auto mt-12">
                            <center>
                                <%= render "history", rentals: @rentals %>
                            </center>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</div>
</div>
</div>
<div id="popup" style="display: none; position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); background: white; padding: 20px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); text-align: right">
    <div style="text-align: left;">
        <h1>Would you like to delete your profile?</h1>
        <p>We hoped you enjoyed your time with VectorBike.</p>
        <div style="display: flex; justify-content: space-around; margin: 0% 25%">
            <%# button to close popup%>
            <div class="button return" onclick="close_popup()">
                Close
            </div>
            <%# button to go through with profile deletion %>
            <%= button_to('Delete Profile', user_path, method: :delete, class: "button") %>
        </div>
    </div>
</div>
</div>
</div>
</div>

<script>
    document.getElementById('checkout-button').addEventListener('click', function() {
        fetch('/create-checkout-session', {
                method: 'POST',
            })
            .then(function(response) {
                return response.json();
            })
            .then(function(sessionId) {
                const stripe = Stripe('pk_test_51QNfAeBdC2IsMXiiJsPSWF48k3gGuIBYmYKqgkutlHrlfbedYz8oLDUPuApV8J4iVdFL0R0kP2zpgw8vQvxgXgjd00eo57lWba'); // Replace with your Stripe publishable key
                stripe.redirectToCheckout({
                    sessionId: sessionId.id
                });
            })
            .catch(function(error) {
                console.error("Error:", error);
            });
    });
</script>